name: WordPress Coding Standards - Blocks

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    name: WordPress Node Linting

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: 'npm'

      - name: Install Node Modules
        run: npm install

      - name: Run Style Lint
        run: npm run lint:css

      - name: Run JavaScript Lint
        run: npm run lint:js
